"""
Django settings for dairyvest project.

Generated by 'django-admin startproject' using Django 5.2.1.

See full docs:
https://docs.djangoproject.com/en/5.2/
"""

from pathlib import Path
from decouple import config
from datetime import timedelta
import cloudinary

# ────────────────────────────────────────────────────────────────────────────────
# BASE DIRECTORY
# ────────────────────────────────────────────────────────────────────────────────
BASE_DIR = Path(__file__).resolve().parent.parent

# ────────────────────────────────────────────────────────────────────────────────
# SECURITY CONFIGURATION
# ────────────────────────────────────────────────────────────────────────────────
SECRET_KEY = config('SECRET_KEY')
DEBUG = config('DEBUG', default=True, cast=bool)
ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

# ────────────────────────────────────────────────────────────────────────────────
# INSTALLED APPS
# ────────────────────────────────────────────────────────────────────────────────
INSTALLED_APPS = [
    # Default Django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'admin_interface',
    'colorfield',  # needed for django-admin-interface


    # Custom apps
    'accounts',
    'sacco',

    # Third-party apps
    'cloudinary',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
]

# ────────────────────────────────────────────────────────────────────────────────
# MIDDLEWARE CONFIGURATION
# ────────────────────────────────────────────────────────────────────────────────
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ────────────────────────────────────────────────────────────────────────────────
# URLS AND WSGI
# ────────────────────────────────────────────────────────────────────────────────
ROOT_URLCONF = 'dairyvest.urls'
WSGI_APPLICATION = 'dairyvest.wsgi.application'

# ────────────────────────────────────────────────────────────────────────────────
# TEMPLATES CONFIGURATION
# ────────────────────────────────────────────────────────────────────────────────
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# ────────────────────────────────────────────────────────────────────────────────
# DATABASE CONFIGURATION (PostgreSQL via python-decouple)
# ────────────────────────────────────────────────────────────────────────────────
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
    }
}

# ────────────────────────────────────────────────────────────────────────────────
# CLOUDINARY CONFIG
# ────────────────────────────────────────────────────────────────────────────────
cloudinary.config(
    cloud_name=config('CLOUDINARY_CLOUD_NAME'),
    api_key=config('CLOUDINARY_API_KEY'),
    api_secret=config('CLOUDINARY_API_SECRET')
)

# ────────────────────────────────────────────────────────────────────────────────
# REST FRAMEWORK + JWT SETTINGS
# ────────────────────────────────────────────────────────────────────────────────
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    # Uncomment below if you want global authentication requirement
    # 'DEFAULT_PERMISSION_CLASSES': [
    #     'rest_framework.permissions.IsAuthenticated',
    # ],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}

# ────────────────────────────────────────────────────────────────────────────────
# CUSTOM USER MODEL
# ────────────────────────────────────────────────────────────────────────────────
AUTH_USER_MODEL = 'accounts.CustomUser'

# ────────────────────────────────────────────────────────────────────────────────
# PASSWORD VALIDATION
# ────────────────────────────────────────────────────────────────────────────────
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ────────────────────────────────────────────────────────────────────────────────
# AUTH BACKENDS
# ────────────────────────────────────────────────────────────────────────────────
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# ────────────────────────────────────────────────────────────────────────────────
# INTERNATIONALIZATION
# ────────────────────────────────────────────────────────────────────────────────
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Africa/Nairobi'
USE_I18N = True
USE_TZ = True

# ────────────────────────────────────────────────────────────────────────────────
# STATIC FILES
# ────────────────────────────────────────────────────────────────────────────────
STATIC_URL = 'static/'

# ────────────────────────────────────────────────────────────────────────────────
# PRIMARY KEY FIELD
# ────────────────────────────────────────────────────────────────────────────────
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'