# Generated by Django 5.2.1 on 2025-05-25 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sacco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='animal',
            name='sacco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='sacco.sacco'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='sacco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='sacco.sacco'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='sacco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='sacco.sacco'),
        ),
        migrations.AlterField(
            model_name='milkproduction',
            name='sacco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_production', to='sacco.sacco'),
        ),
    ]
